### ISSUE TITLE
The type or namespace name 'Controls' does not exist

### ISSUE THREAD

**Issue by jrahma** [Redth/ZXing.Net.Maui#59]
Hi,

I don't know why I started getting the below message in 0.2.0-preview.2

`Error CS0234: The type or namespace name 'Controls' does not exist in the namespace 'ZXing.Net.Maui' (are you missing an assembly reference?) (CS0234)`

This is the line throwing the error:

`xmlns:zxing="clr-namespace:ZXing.Net.Maui.Controls;assembly=ZXing.Net.MAUI"
`

Kindly help..

Thanks,
Jassim

**Comment by g0dpain** [comment]
https://github.com/Redth/ZXing.Net.Maui/issues/55

Please download [ZXing.Net.Maui.Controls](https://www.nuget.org/packages/ZXing.Net.Maui.Controls/0.2.0-preview.2) and change ``xmlns:zxing="clr-namespace:ZXing.Net.Maui.Controls;assembly=ZXing.Net.MAUI"`` to ``xmlns:zxing="clr-namespace:ZXing.Net.Maui.Controls;assembly=ZXing.Net.Maui.Controls"``

**Comment by jmSfernandes** [comment]
I'am facing the same issue when updating from 0.1.0-preview7.
The extension `.UseBarcodeReader();` for the MauiAppBuilder is not included as well.

Have the dependencies been moved to another package? 
And if so, wouldn't it be better to have them as a dependency of Zxing.Net.Maui, 
so that they are installed automatically?
